### ISSUE TITLE
ASP.NET Core API Not working with Africa's Talking USSD Service

### ISSUE THREAD

**Issue by Jcardif** [AfricasTalkingLtd/africastalking.Net#46]
I created a dotnet core API to provide the callback URL for the USSD Service. But the API does not work the USSD Services gives the error below: 
![image](https://user-images.githubusercontent.com/29174946/85443198-a4ef6e80-b599-11ea-8cf9-6c5f545f2070.png)

My controller is designed as follows:
```csharp

 [Route("api/[controller]")]
    [ApiController]
    public class ServicesController : ControllerBase
    {
        [Route("ussd")]
        [HttpPost]
        public IActionResult USSDService([FromBody] USSDResponse serviceResponse)
        {

        }
    }

```

However the USSD service works when the method is changed as follows:

```csharp
        public IActionResult USSDService(string serviceResponse)
        {

        }
```
But the issue is that no object is passed from the USSD Service to this method

**Comment by TheBeachMaster** [comment]
@Jcardif  see example on [step 7](https://github.com/AfricasTalkingLtd/africastalking.Net#building-a-ussd-application)
