### ISSUE TITLE
The message is either empty or phone number is not valid - with valid phone number

### ISSUE THREAD

**Issue by XardasLord** [AfricasTalkingLtd/africastalking.Net#48]
Sometimes I'm getting the following error message from your library: **_"The message is either empty or phone number is not valid"_**, but the number is valid and exists, for example for number **"+254111604133"**.

Is there something wrong with your logic which validates the phone number?

I'm using the AfricasTalking.NET in version 1.1.720.

**Comment by XardasLord** [comment]
As far as I know from our client from Kenya the Safaricom introduced new prefixes (254111 and 254110) to phone numbers. Africa's Talking claims to have added these prefixes to their database.

**Comment by TheBeachMaster** [comment]
Hi @XardasLord ,

Noted, an update to the phone number library will be made.

**Comment by TheBeachMaster** [comment]
@XardasLord  this will be fixed in the next package update `v1.2.1` pending this issue > https://github.com/brandedoutcast/publish-nuget/issues/51
